version: "3"

services:
  front:
    image: file-notary-frontend:latest
    ports:
      - "80:80"

  notary:
    image: file-notary-backend:latest
    env_file: ".env"
    environment:
      MONGO_HOST: mongo:27017
    volumes:
      - ./contract/artifacts:/app/artifacts
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
