version: "3"

services:
  front:
    image: file-notary-frontend:latest
    ports:
      - "80:80"

  notary:
    image: file-notary-backend:latest
    env_file: ".env"
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
